/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import model.dao.CustomerInfoDAO;
import model.dao.CylinderTypeDAO;
import model.to.CustomerInfoTO;
import model.to.CylinderTypeTO;
import operational.Checks;

/**
 *
 * @author Grapess
 */
public class AddCustomerInfo extends javax.swing.JInternalFrame {

    CustomerInfoTO updateData;

    public AddCustomerInfo() {
        initComponents();
        setSize(850, 600);
        bindCylinderType();
    }

    public AddCustomerInfo(CustomerInfoTO data) {
        this();
        this.updateData = data;
        if (data != null) {
            btnAdd.setText("Update Customer Info");
            jtfCustomerName.setText(data.getCustomerName());
            jtfColonyName.setText(data.getColonyName());
            jtfContactNo.setText(data.getContactNo());
            jtfAddress.setText(data.getAddress());
            jtfNoOfCylinder.setText(String.valueOf(data.getNoOfCylinder()));
            for (int i = 1; i <= jcbCylinderType.getItemCount(); i++) {
                CylinderTypeTO ctt = (CylinderTypeTO) jcbCylinderType.getItemAt(i);
                if (ctt.getTypeID().equalsIgnoreCase(updateData.getTypeID())) {
                    jcbCylinderType.setSelectedIndex(i);
                    break;
                }
            }
        }
    }

    private void bindCylinderType() {
        jcbCylinderType.removeAllItems();
        jcbCylinderType.addItem("Select A Type");
        ArrayList<CylinderTypeTO> allTypes = new CylinderTypeDAO().getAllRecord();
        if (allTypes != null) {
            for (CylinderTypeTO ctt : allTypes) {
                jcbCylinderType.addItem(ctt);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jtfNoOfCylinder = new javax.swing.JTextField();
        jtfCustomerName = new javax.swing.JTextField();
        jtfColonyName = new javax.swing.JTextField();
        jtfAddress = new javax.swing.JTextField();
        jtfContactNo = new javax.swing.JTextField();
        jcbCylinderType = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Customer Info");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Enter No Of Cylinder :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 330, 300, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Enter Customer Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 30, 300, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Enter Colony Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 90, 300, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Enter Address :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 150, 300, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Enter Contact No :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 210, 300, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Choose Cylinder Type :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 270, 300, 29);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAdd.setText("Add Customer Info");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(160, 380, 450, 70);

        jtfNoOfCylinder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNoOfCylinderKeyTyped(evt);
            }
        });
        getContentPane().add(jtfNoOfCylinder);
        jtfNoOfCylinder.setBounds(380, 330, 350, 30);
        getContentPane().add(jtfCustomerName);
        jtfCustomerName.setBounds(380, 30, 350, 30);
        getContentPane().add(jtfColonyName);
        jtfColonyName.setBounds(380, 90, 350, 30);
        getContentPane().add(jtfAddress);
        jtfAddress.setBounds(380, 150, 350, 30);

        jtfContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfContactNoKeyTyped(evt);
            }
        });
        getContentPane().add(jtfContactNo);
        jtfContactNo.setBounds(380, 210, 350, 30);

        jcbCylinderType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbCylinderType);
        jcbCylinderType.setBounds(380, 270, 350, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfContactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContactNoKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            if (evt.getKeyChar() != '\b') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtfContactNoKeyTyped

    private void jtfNoOfCylinderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNoOfCylinderKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            if (evt.getKeyChar() != '\b') {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jtfNoOfCylinderKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String message = "";
        try {
            String customername = jtfCustomerName.getText().trim();
            String colonyName = jtfColonyName.getText().trim();
            String address = jtfAddress.getText().trim();
            String contactNo = jtfContactNo.getText().trim();
            String noOfCylinder = jtfNoOfCylinder.getText().trim();
            if (Checks.isEmpty(customername) || Checks.isEmpty(colonyName) || Checks.isEmpty(address) || Checks.isEmpty(contactNo) || Checks.isEmpty(noOfCylinder)) {
                message = "Please Fill All Boxes";
            } else if (!(jcbCylinderType.getSelectedItem() instanceof CylinderTypeTO)) {
                message = "Please Choose Any Cylinder Type";
            } else if (Checks.isNumeric(noOfCylinder)) {
                CylinderTypeTO ctt = (CylinderTypeTO) jcbCylinderType.getSelectedItem();
                CustomerInfoTO data = new CustomerInfoTO();
                data.setCustomerName(customername);
                data.setColonyName(colonyName);
                data.setAddress(address);
                data.setContactNo(contactNo);
                data.setTypeID(ctt.getTypeID());
                data.setNoOfCylinder(Integer.parseInt(noOfCylinder));
                CustomerInfoDAO action = new CustomerInfoDAO();
                if (btnAdd.getText().contains("Add")) {
                    if (action.insertRecord(data)) {
                        message = " Customer Info is Added in the System";
                    } else {
                        message = action.getErrorMessage();
                    }
                } else if (btnAdd.getText().contains("Update")) {
                    if (updateData != null) {
                        data.setCustomerID(updateData.getCustomerID());
                        if (action.updateRecord(data)) {
                            message = " Customer Info is Updated in the System";
                            ViewCustomerInfo obj = new ViewCustomerInfo();
                            obj.setVisible(true);
                            JDesktopPane jdp = getDesktopPane();
                            jdp.add(obj);
                            try {
                                obj.setSelected(true);
                            } catch (PropertyVetoException ex) {
                            }
                            dispose();
                        } else {
                            message = action.getErrorMessage();
                        }
                    } else {
                        message = " Not Allowed Operation ";
                    }
                }
            } else {
                message = "Please Enter Numeric Value in No of Cylinder Box";
            }
        } catch (Exception ex) {
            message = ex.getMessage();
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox jcbCylinderType;
    private javax.swing.JTextField jtfAddress;
    private javax.swing.JTextField jtfColonyName;
    private javax.swing.JTextField jtfContactNo;
    private javax.swing.JTextField jtfCustomerName;
    private javax.swing.JTextField jtfNoOfCylinder;
    // End of variables declaration//GEN-END:variables
}
