/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import javax.swing.JInternalFrame;

/**
 *
 * @author Grapess
 */
public class AdminScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminScreen
     */
    public AdminScreen() {
        initComponents();
        setTitle("Gas Agency");
        setSize(1000,700);
        setLocationRelativeTo(null);
    }

    private void displayScreen(JInternalFrame frame){
        try{
            frame.setVisible(true);
          //  desktopPane2.add(frame);
            frame.setSelected(true);
        }catch(Exception ex){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane1 = new admin.ui.DesktopPane();
        desktopPane3 = new admin.ui.DesktopPane();
        desktopPane4 = new admin.ui.DesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmiAddUserInfo = new javax.swing.JMenuItem();
        jmiViewUserInfo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiAddCylinderType = new javax.swing.JMenuItem();
        jmiViewCylinderType = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiAddCustomerInfo = new javax.swing.JMenuItem();
        jmiViewCustomerInfo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiAddCylinderInfo = new javax.swing.JMenuItem();
        jmiViewCylinderInfo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiAddCylinderStock = new javax.swing.JMenuItem();
        jmiViewCylinderStock = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiAddBillInfo = new javax.swing.JMenuItem();
        jmiViewBillInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(desktopPane4, java.awt.BorderLayout.CENTER);

        jMenu2.setText("Login Info");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jmiAddUserInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmiAddUserInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/addd.png"))); // NOI18N
        jmiAddUserInfo.setText("Add User Info");
        jmiAddUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddUserInfoActionPerformed(evt);
            }
        });
        jMenu2.add(jmiAddUserInfo);

        jmiViewUserInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmiViewUserInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/vieww.png"))); // NOI18N
        jmiViewUserInfo.setText("View User Info");
        jmiViewUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewUserInfoActionPerformed(evt);
            }
        });
        jMenu2.add(jmiViewUserInfo);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Cylinder Type");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jmiAddCylinderType.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmiAddCylinderType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/addd.png"))); // NOI18N
        jmiAddCylinderType.setText("Add Cylinder Type");
        jmiAddCylinderType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddCylinderTypeActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAddCylinderType);

        jmiViewCylinderType.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmiViewCylinderType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/vieww.png"))); // NOI18N
        jmiViewCylinderType.setText("View Cylinder Type");
        jmiViewCylinderType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewCylinderTypeActionPerformed(evt);
            }
        });
        jMenu1.add(jmiViewCylinderType);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Customer Info");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jmiAddCustomerInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmiAddCustomerInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/addd.png"))); // NOI18N
        jmiAddCustomerInfo.setText("Add Customer Info");
        jmiAddCustomerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddCustomerInfoActionPerformed(evt);
            }
        });
        jMenu3.add(jmiAddCustomerInfo);

        jmiViewCustomerInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmiViewCustomerInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/vieww.png"))); // NOI18N
        jmiViewCustomerInfo.setText("View Customer Info");
        jmiViewCustomerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewCustomerInfoActionPerformed(evt);
            }
        });
        jMenu3.add(jmiViewCustomerInfo);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Cylinder Info");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jmiAddCylinderInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmiAddCylinderInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/addd.png"))); // NOI18N
        jmiAddCylinderInfo.setText("Add Cylinder Info");
        jmiAddCylinderInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddCylinderInfoActionPerformed(evt);
            }
        });
        jMenu4.add(jmiAddCylinderInfo);

        jmiViewCylinderInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmiViewCylinderInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/vieww.png"))); // NOI18N
        jmiViewCylinderInfo.setText("View Cylinder Info");
        jmiViewCylinderInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewCylinderInfoActionPerformed(evt);
            }
        });
        jMenu4.add(jmiViewCylinderInfo);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Cylinder Stock");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jmiAddCylinderStock.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmiAddCylinderStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/addd.png"))); // NOI18N
        jmiAddCylinderStock.setText("Add Cylinder Stock");
        jmiAddCylinderStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddCylinderStockActionPerformed(evt);
            }
        });
        jMenu5.add(jmiAddCylinderStock);

        jmiViewCylinderStock.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmiViewCylinderStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/vieww.png"))); // NOI18N
        jmiViewCylinderStock.setText("View Cylinder Stock");
        jmiViewCylinderStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewCylinderStockActionPerformed(evt);
            }
        });
        jMenu5.add(jmiViewCylinderStock);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Bill Info");
        jMenu6.setToolTipText("");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(75, 39));

        jmiAddBillInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmiAddBillInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/addd.png"))); // NOI18N
        jmiAddBillInfo.setText("Add Bill Info");
        jmiAddBillInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddBillInfoActionPerformed(evt);
            }
        });
        jMenu6.add(jmiAddBillInfo);

        jmiViewBillInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jmiViewBillInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/ui/vieww.png"))); // NOI18N
        jmiViewBillInfo.setText("View Bill Info");
        jmiViewBillInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewBillInfoActionPerformed(evt);
            }
        });
        jMenu6.add(jmiViewBillInfo);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAddUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddUserInfoActionPerformed
        displayScreen(new AddUserInfo());
    }//GEN-LAST:event_jmiAddUserInfoActionPerformed

    private void jmiAddCylinderTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddCylinderTypeActionPerformed
        displayScreen(new AddCylinderType());
    }//GEN-LAST:event_jmiAddCylinderTypeActionPerformed

    private void jmiViewUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewUserInfoActionPerformed
        displayScreen(new ViewUserInfo());
    }//GEN-LAST:event_jmiViewUserInfoActionPerformed

    private void jmiViewCylinderTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewCylinderTypeActionPerformed
        displayScreen(new ViewCylinderType());
    }//GEN-LAST:event_jmiViewCylinderTypeActionPerformed

    private void jmiAddCustomerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddCustomerInfoActionPerformed
        displayScreen(new AddCustomerInfo());
    }//GEN-LAST:event_jmiAddCustomerInfoActionPerformed

    private void jmiViewCustomerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewCustomerInfoActionPerformed
        displayScreen(new ViewCustomerInfo());
    }//GEN-LAST:event_jmiViewCustomerInfoActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jmiAddCylinderInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddCylinderInfoActionPerformed
        displayScreen(new AddCylinderInfo());
    }//GEN-LAST:event_jmiAddCylinderInfoActionPerformed

    private void jmiViewCylinderInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewCylinderInfoActionPerformed
        displayScreen(new ViewCylinderInfo());
    }//GEN-LAST:event_jmiViewCylinderInfoActionPerformed

    private void jmiViewCylinderStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewCylinderStockActionPerformed
        displayScreen(new ViewCylinderStock());
    }//GEN-LAST:event_jmiViewCylinderStockActionPerformed

    private void jmiAddCylinderStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddCylinderStockActionPerformed
        displayScreen(new AddCylinderStock());
    }//GEN-LAST:event_jmiAddCylinderStockActionPerformed

    private void jmiViewBillInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewBillInfoActionPerformed
        displayScreen(new ViewBillInfo());
    }//GEN-LAST:event_jmiViewBillInfoActionPerformed

    private void jmiAddBillInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddBillInfoActionPerformed
        displayScreen(new AddBillInfo());
    }//GEN-LAST:event_jmiAddBillInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private admin.ui.DesktopPane desktopPane1;
    private admin.ui.DesktopPane desktopPane3;
    private admin.ui.DesktopPane desktopPane4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAddBillInfo;
    private javax.swing.JMenuItem jmiAddCustomerInfo;
    private javax.swing.JMenuItem jmiAddCylinderInfo;
    private javax.swing.JMenuItem jmiAddCylinderStock;
    private javax.swing.JMenuItem jmiAddCylinderType;
    private javax.swing.JMenuItem jmiAddUserInfo;
    private javax.swing.JMenuItem jmiViewBillInfo;
    private javax.swing.JMenuItem jmiViewCustomerInfo;
    private javax.swing.JMenuItem jmiViewCylinderInfo;
    private javax.swing.JMenuItem jmiViewCylinderStock;
    private javax.swing.JMenuItem jmiViewCylinderType;
    private javax.swing.JMenuItem jmiViewUserInfo;
    // End of variables declaration//GEN-END:variables
}
