/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.dao.CustomerInfoDAO;
import model.dao.CylinderInfoDAO;
import model.to.CustomerInfoTO;
import model.to.CylinderInfoTO;

/**
 *
 * @author Grapess
 */
public class ViewCylinderInfo extends javax.swing.JInternalFrame {

    ArrayList<CylinderInfoTO> allCylinders;
    JPopupMenu myMenu;
    int row;
    public ViewCylinderInfo() {
        initComponents();
        setSize(850,600);
        refreshTable();
        myMenu = new JPopupMenu();
        JMenuItem jmiUpdate = new JMenuItem("Update This Record");
        myMenu.add(jmiUpdate);
        JMenuItem jmiDelete = new JMenuItem("Delete This Record");
        myMenu.add(jmiDelete);
        row = -1;
        jmiUpdate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateRecord();
            }
        });
        jmiDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });
    }

    private void refreshTable(){
        String[] headerNames = {"Company Name", "Type Name", "Weight", "Price", "Fill Cylinder", "Empty Cylinder"};
        allCylinders = new CylinderInfoDAO().getAllRecord();
        if (allCylinders != null) {
            int size = allCylinders.size();
            Object[][] datas = new Object[size][headerNames.length];
            int index = 0;
            for (CylinderInfoTO cit : allCylinders) {
                datas[index] = new Object[headerNames.length];
                datas[index][0] = cit.getCompanyName();
                datas[index][1] = cit.getTypeName();
                datas[index][2] = cit.getWeight();
                datas[index][3] = cit.getPrice();
                datas[index][4] = cit.getFilledQty();
                datas[index][5] = cit.getEmptyQty();
                index++;
            }
            jtCylinderInfo.setModel(new DefaultTableModel(datas, headerNames));
        } else {
            Object[][] datas = new Object[1][headerNames.length];
            datas[0] = new Object[headerNames.length];
            datas[0][0] = "NO DATA";
            datas[0][1] = "NO DATA";
            datas[0][2] = "NO DATA";
            datas[0][3] = "NO DATA";
            datas[0][4] = "NO DATA";
            datas[0][5] = "NO DATA";
            jtCylinderInfo.setModel(new DefaultTableModel(datas, headerNames));
        }
    }
    
    private void updateRecord(){
        try {
            if (row != -1) {
                CylinderInfoTO data = allCylinders.get(row);
                if (data != null) {
                    AddCylinderInfo obj = new AddCylinderInfo(data);
                    obj.setVisible(true);
                    obj.setTitle("Update Cylinder Info");
                    JDesktopPane jdp = getDesktopPane();
                    jdp.add(obj);
                    try {
                        obj.setSelected(true);
                    } catch (PropertyVetoException ex) {
                    }
                    dispose();
                }
            }
        } catch (Exception ex) {
        }
    }
    
    private void deleteRecord(){
        try {
            if (row != -1) {
                CylinderInfoTO data = allCylinders.get(row);
                if (data != null) {
                    int option = JOptionPane.showConfirmDialog(this, " Are You Sure To Delete This Record?");
                    if (option == JOptionPane.OK_OPTION) {
                        CylinderInfoDAO action = new CylinderInfoDAO();
                        if (action.deleteRecord(data.getCylinderID())) {
                            JOptionPane.showMessageDialog(this, "Deletion Happen");
                            refreshTable();
                        } else {
                            JOptionPane.showMessageDialog(this, action.getErrorMessage());
                        }
                    }
                }
            }
        } catch (Exception ex) {
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtCylinderInfo = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("View Cylinder Info");

        jtCylinderInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtCylinderInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtCylinderInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCylinderInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtCylinderInfo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCylinderInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCylinderInfoMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            int idx = jtCylinderInfo.rowAtPoint(evt.getPoint());
            jtCylinderInfo.getSelectionModel().setSelectionInterval(idx, idx);
            row = jtCylinderInfo.getSelectedRow();
            myMenu.show(jtCylinderInfo, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jtCylinderInfoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtCylinderInfo;
    // End of variables declaration//GEN-END:variables
}
