/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.dao.CylinderInfoDAO;
import model.dao.CylinderStockDAO;
import model.to.CylinderInfoTO;
import model.to.CylinderStockTO;

/**
 *
 * @author Grapess
 */
public class ViewCylinderStock extends javax.swing.JInternalFrame {

    ArrayList<CylinderStockTO> allCylinderStock;
    public ViewCylinderStock() {
        initComponents();
        setSize(850,600);
        refreshTable();
    }
    private void refreshTable(){
        String[] headerNames = {"Company Name", "Stock Type", "Cylinder Status", "Quantity", "Stock Date"};
        allCylinderStock = new CylinderStockDAO().getAllRecord();
        if (allCylinderStock != null) {
            int size = allCylinderStock.size();
            Object[][] datas = new Object[size][headerNames.length];
            int index = 0;
            for (CylinderStockTO cit : allCylinderStock) {
                datas[index] = new Object[headerNames.length];
                datas[index][0] = cit.getCompanyName();
                datas[index][1] = cit.getStockType();
                datas[index][2] = cit.getCylinderStatus();
                datas[index][3] = cit.getQuantity();
                datas[index][4] = cit.getStockDate();
                
                index++;
            }
            jtCylinderStock.setModel(new DefaultTableModel(datas, headerNames));
        } else {
            Object[][] datas = new Object[1][headerNames.length];
            datas[0] = new Object[headerNames.length];
            datas[0][0] = "NO DATA";
            datas[0][1] = "NO DATA";
            datas[0][2] = "NO DATA";
            datas[0][3] = "NO DATA";
            datas[0][4] = "NO DATA";
            jtCylinderStock.setModel(new DefaultTableModel(datas, headerNames));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtCylinderStock = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("View Cylinder Stock");

        jtCylinderStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtCylinderStock);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtCylinderStock;
    // End of variables declaration//GEN-END:variables
}
