/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.dao.BillInfoDAO;
import model.dao.CustomerInfoDAO;
import model.to.BillInfoTO;
import model.to.CustomerInfoTO;

/**
 *
 * @author Grapess
 */
public class ViewBillInfo extends javax.swing.JInternalFrame {

    ArrayList<BillInfoTO> allBills;
    JPopupMenu myMenu;
    int row;

    public ViewBillInfo() {
        initComponents();
        setSize(850, 600);
        refreshTable();
        myMenu = new JPopupMenu();
        
        JMenuItem jmiDelete = new JMenuItem("Delete This Record");
        myMenu.add(jmiDelete);
        row = -1;
      
        jmiDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });
    }
    
    private void refreshTable(){
        String[] headerNames = {"Bill No", "Customer Name", "Company Name", "Cylinder No", "Quantity", "Price","Bill Date"};
        allBills = new BillInfoDAO().getAllRecord();
        if (allBills != null) {
            int size = allBills.size();
            Object[][] datas = new Object[size][headerNames.length];
            int index = 0;
            for (BillInfoTO cit : allBills) {
                datas[index] = new Object[headerNames.length];
                datas[index][0] = cit.getBillID();
                datas[index][1] = cit.getCustomerName();
                datas[index][2] = cit.getCompanyName();
                datas[index][3] = cit.getCylinderNo();
                datas[index][4] = cit.getQuantity();
                datas[index][5] = cit.getPrice();
                datas[index][6] = cit.getBillDate();
                index++;
            }
            jtBillInfo.setModel(new DefaultTableModel(datas, headerNames));
        } else {
            Object[][] datas = new Object[1][headerNames.length];
            datas[0] = new Object[headerNames.length];
            datas[0][0] = "NO DATA";
            datas[0][1] = "NO DATA";
            datas[0][2] = "NO DATA";
            datas[0][3] = "NO DATA";
            datas[0][4] = "NO DATA";
            datas[0][5] = "NO DATA";
            datas[0][6] = "NO DATA";
            jtBillInfo.setModel(new DefaultTableModel(datas, headerNames));
        }
    }
    
    private void deleteRecord(){
        try {
            if (row != -1) {
                BillInfoTO data = allBills.get(row);
                if (data != null) {
                    int option = JOptionPane.showConfirmDialog(this, " Are You Sure To Delete This Record?");
                    if (option == JOptionPane.OK_OPTION) {
                        BillInfoDAO action = new BillInfoDAO();
                        if (action.deleteRecord(data.getBillID())) {
                            JOptionPane.showMessageDialog(this, "Deletion Happen");
                            refreshTable();
                        } else {
                            JOptionPane.showMessageDialog(this, action.getErrorMessage());
                        }
                    }
                }
            }
        } catch (Exception ex) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtBillInfo = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("View Bill Info");

        jtBillInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtBillInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtBillInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtBillInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtBillInfo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtBillInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtBillInfoMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            int idx = jtBillInfo.rowAtPoint(evt.getPoint());
            jtBillInfo.getSelectionModel().setSelectionInterval(idx, idx);
            row = jtBillInfo.getSelectedRow();
            myMenu.show(jtBillInfo, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jtBillInfoMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtBillInfo;
    // End of variables declaration//GEN-END:variables
}
