/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import java.beans.PropertyVetoException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import model.dao.CylinderTypeDAO;
import model.to.CylinderTypeTO;
import operational.Checks;

/**
 *
 * @author Grapess
 */
public class AddCylinderType extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddCylinderType
     */
    public AddCylinderType() {
        initComponents();
        setSize(850, 600);
    }
    CylinderTypeTO updateData;

    public AddCylinderType(CylinderTypeTO data) {
        this();
        this.updateData = data;
        if (data != null) {
            jtfTypeID.setText(data.getTypeID());
            jtfTypeName.setText(data.getTypeName());
            jtfTypeID.setEnabled(false);
            btnAdd.setText("Update This Record");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfTypeName = new javax.swing.JTextField();
        jtfTypeID = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Cylinder Type");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Enter Cylinder Type Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 160, 340, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Enter Type ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 70, 290, 29);
        getContentPane().add(jtfTypeName);
        jtfTypeName.setBounds(400, 160, 250, 40);
        getContentPane().add(jtfTypeID);
        jtfTypeID.setBounds(400, 70, 250, 40);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAdd.setText("Add Cylinder Type");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(100, 240, 490, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String message = "";
        try {
            String typeid = jtfTypeID.getText().trim();
            String typename = jtfTypeName.getText().trim();
            if (Checks.isEmpty(typeid) || Checks.isEmpty(typename)) {
                message = "Please Enter Some Value";
            } else {
                CylinderTypeTO data = new CylinderTypeTO();
                data.setTypeID(typeid);
                data.setTypeName(typename);
                CylinderTypeDAO action = new CylinderTypeDAO();
                if (btnAdd.getText().contains("Add")) {
                    if (action.insertRecord(data)) {
                        message = " Cylinder Type is Added Successfully ";
                    } else {
                        message = action.getErrorMessage();
                    }
                } else if (btnAdd.getText().contains("Update")) {
                    if (action.updateRecord(data)) {
                        message = " Cylinder Type is Updated Successfully ";
                        ViewCylinderType obj = new ViewCylinderType();
                        obj.setVisible(true);
                        JDesktopPane jdp = getDesktopPane();
                        jdp.add(obj);
                        try {
                            obj.setSelected(true);
                        } catch (PropertyVetoException ex) {
                        }
                        dispose();
                    } else {
                        message = action.getErrorMessage();
                    }
                }
            }
        } catch (Exception ex) {
            message = ex.getMessage();
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtfTypeID;
    private javax.swing.JTextField jtfTypeName;
    // End of variables declaration//GEN-END:variables
}
