/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import model.dao.CylinderInfoDAO;
import model.dao.CylinderTypeDAO;
import model.to.CylinderInfoTO;
import model.to.CylinderTypeTO;
import operational.Checks;

/**
 *
 * @author Grapess
 */
public class AddCylinderInfo extends javax.swing.JInternalFrame {

    CylinderInfoTO updateData;

    public AddCylinderInfo() {
        initComponents();
        setSize(850, 600);
        bindCylinderType();
    }

    private void bindCylinderType() {
        jcbCylinderType.removeAllItems();
        jcbCylinderType.addItem("Select A Type");
        ArrayList<CylinderTypeTO> allTypes = new CylinderTypeDAO().getAllRecord();
        if (allTypes != null) {
            for (CylinderTypeTO ctt : allTypes) {
                jcbCylinderType.addItem(ctt);
            }
        }
    }

    public AddCylinderInfo(CylinderInfoTO data) {
        this();
        this.updateData = data;
        if (data != null) {
            jtfCompanyName.setText(data.getCompanyName());
            jtfPrice.setText(String.valueOf(data.getPrice()));
            jtfWeight.setText(String.valueOf(data.getWeight()));
            btnAdd.setText("Update Cylinder Info");
            for (int i = 1; i <= jcbCylinderType.getItemCount(); i++) {
                CylinderTypeTO ctt = (CylinderTypeTO) jcbCylinderType.getItemAt(i);
                if (ctt.getTypeID().equalsIgnoreCase(data.getTypeID())) {
                    jcbCylinderType.setSelectedIndex(i);
                    break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfWeight = new javax.swing.JTextField();
        jtfCompanyName = new javax.swing.JTextField();
        jtfPrice = new javax.swing.JTextField();
        jcbCylinderType = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Cylinder Info");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Enter Cylinder Weight :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 250, 300, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Enter Company Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 50, 290, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Choose Cylinder Type :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 110, 290, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Enter Cylinder Price :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 180, 290, 29);
        getContentPane().add(jtfWeight);
        jtfWeight.setBounds(350, 250, 290, 30);
        getContentPane().add(jtfCompanyName);
        jtfCompanyName.setBounds(350, 50, 290, 30);
        getContentPane().add(jtfPrice);
        jtfPrice.setBounds(350, 180, 290, 30);

        jcbCylinderType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbCylinderType);
        jcbCylinderType.setBounds(350, 110, 290, 40);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAdd.setText("Add Cylinder Info");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(110, 320, 470, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String message = "";
        try {
            String companyname = jtfCompanyName.getText().trim();
            String price = jtfPrice.getText().trim();
            String weight = jtfWeight.getText().trim();
            if (Checks.isEmpty(companyname) || Checks.isEmpty(price) || Checks.isEmpty(weight)) {
                message = "Please Fill All Text Boxes";
            } else if (!(jcbCylinderType.getSelectedItem() instanceof CylinderTypeTO)) {
                message = "Please Choose Any Cylinder Type";
            } else if (Checks.isFloatNumeric(price) && Checks.isFloatNumeric(weight)) {
                CylinderInfoTO data = new CylinderInfoTO();
                CylinderTypeTO ctt = (CylinderTypeTO) jcbCylinderType.getSelectedItem();
                data.setCompanyName(companyname);
                data.setPrice(Float.parseFloat(price));
                data.setWeight(Float.parseFloat(weight));
                data.setTypeID(ctt.getTypeID());
                CylinderInfoDAO action = new CylinderInfoDAO();
                if (btnAdd.getText().contains("Add")) {
                    if (action.insertRecord(data)) {
                        message = " Cylinder Info is Added into the System";
                    } else {
                        message = action.getErrorMessage();
                    }
                } else if (btnAdd.getText().contains("Update")) {
                    if (updateData != null) {
                        data.setCylinderID(updateData.getCylinderID());
                        if (action.updateRecord(data)) {
                            message = " Cylinder Info is Updated into the System";
                            ViewCylinderInfo obj = new ViewCylinderInfo();
                            obj.setVisible(true);
                            JDesktopPane jdp = getDesktopPane();
                            jdp.add(obj);
                            try {
                                obj.setSelected(true);
                            } catch (PropertyVetoException ex) {
                            }
                            dispose();
                        } else {
                            message = action.getErrorMessage();
                        }
                    } else {
                        message = "Not Allowed Operation";
                    }
                }
            } else {
                message = "Please Enter Numeric value in price and weight box";
            }
        } catch (Exception ex) {
            message = ex.getMessage();
        }
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnAddActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox jcbCylinderType;
    private javax.swing.JTextField jtfCompanyName;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JTextField jtfWeight;
    // End of variables declaration//GEN-END:variables
}
