/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.dao.CustomerInfoDAO;
import model.dao.CylinderTypeDAO;
import model.to.CustomerInfoTO;
import model.to.CylinderTypeTO;

/**
 *
 * @author Grapess
 */
public class ViewCustomerInfo extends javax.swing.JInternalFrame {

    ArrayList<CustomerInfoTO> allCustomers;
    JPopupMenu myMenu;
    int row;

    public ViewCustomerInfo() {
        initComponents();
        refreshTable();
        myMenu = new JPopupMenu();
        JMenuItem jmiUpdate = new JMenuItem("Update This Record");
        myMenu.add(jmiUpdate);
        JMenuItem jmiDelete = new JMenuItem("Delete This Record");
        myMenu.add(jmiDelete);
        row = -1;
        jmiUpdate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateRecord();
            }
        });
        jmiDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteRecord();
            }
        });
    }

    private void updateRecord() {
        try {
            if (row != -1) {
                CustomerInfoTO data = allCustomers.get(row);
                if (data != null) {
                    AddCustomerInfo obj = new AddCustomerInfo(data);
                    obj.setVisible(true);
                    obj.setTitle("Update Customer Info");
                    JDesktopPane jdp = getDesktopPane();
                    jdp.add(obj);
                    try {
                        obj.setSelected(true);
                    } catch (PropertyVetoException ex) {
                    }
                    dispose();
                }
            }
        } catch (Exception ex) {
        }
    
    }

    private void deleteRecord() {
        try {
            if (row != -1) {
                CustomerInfoTO data = allCustomers.get(row);
                if (data != null) {
                    int option = JOptionPane.showConfirmDialog(this, " Are You Sure To Delete This Record?");
                    if (option == JOptionPane.OK_OPTION) {
                        CustomerInfoDAO action = new CustomerInfoDAO();
                        if (action.deleteRecord(data.getCustomerID())) {
                            JOptionPane.showMessageDialog(this, "Deletion Happen");
                            refreshTable();
                        } else {
                            JOptionPane.showMessageDialog(this, action.getErrorMessage());
                        }
                    }
                }
            }
        } catch (Exception ex) {
        }

    }

    private void refreshTable() {
        String[] headerNames = {"Customer Name", "Colony Name", "Address", "Contact No", "Type Name", "No Of Cylinder"};
        allCustomers = new CustomerInfoDAO().getAllRecord();
        if (allCustomers != null) {
            int size = allCustomers.size();
            Object[][] datas = new Object[size][headerNames.length];
            int index = 0;
            for (CustomerInfoTO cit : allCustomers) {
                datas[index] = new Object[headerNames.length];
                datas[index][0] = cit.getCustomerName();
                datas[index][1] = cit.getColonyName();
                datas[index][2] = cit.getAddress();
                datas[index][3] = cit.getContactNo();
                datas[index][4] = cit.getTypeName();
                datas[index][5] = cit.getNoOfCylinder();
                index++;
            }
            jtCustomerInfo.setModel(new DefaultTableModel(datas, headerNames));
        } else {
            Object[][] datas = new Object[1][headerNames.length];
            datas[0] = new Object[headerNames.length];
            datas[0][0] = "NO DATA";
            datas[0][1] = "NO DATA";
            datas[0][2] = "NO DATA";
            datas[0][3] = "NO DATA";
            datas[0][4] = "NO DATA";
            datas[0][5] = "NO DATA";
            jtCustomerInfo.setModel(new DefaultTableModel(datas, headerNames));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtCustomerInfo = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("View Customer Info");

        jtCustomerInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtCustomerInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtCustomerInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCustomerInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtCustomerInfo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCustomerInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCustomerInfoMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            int idx = jtCustomerInfo.rowAtPoint(evt.getPoint());
            jtCustomerInfo.getSelectionModel().setSelectionInterval(idx, idx);
            row = jtCustomerInfo.getSelectedRow();
            myMenu.show(jtCustomerInfo, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jtCustomerInfoMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtCustomerInfo;
    // End of variables declaration//GEN-END:variables
}
